CREATE TABLE IF NOT EXISTS docs (
  id INT PRIMARY KEY AUTO_INCREMENT,
  titulo VARCHAR(255) NOT NULL,
  conteudo TEXT NOT NULL,
  embedding JSON NOT NULL,
  fonte VARCHAR(255) DEFAULT 'Manual Emptum',
  criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
